// packages/react/src/base/StatePresetBlock.tsx
/**
 * `StatePresetBlock` 是旧场景包装组件共用的桥接层。
 * 它根据 `blockId` 从 shared 元数据里取出默认配置，再和调用方传入的覆盖 props 合并。
 */
import {
  stateBlockMetaById,
  type BaseStateProps,
  type StateBlockId,
} from "@statekit-vue/shared";
import { mergeStateProps } from "../lib/merge-state-props";
import type { PresetStateBlockProps } from "../types";
import { StateBlockShell } from "./StateBlockShell";

export interface StatePresetBlockProps extends PresetStateBlockProps {
  /** 指向某个预设元数据的稳定 id，是这个桥接层的唯一必填字段。 */
  blockId: StateBlockId;
}

export function StatePresetBlock({
  blockId,
  media,
  actions,
  ...props
}: StatePresetBlockProps) {
  const blockMeta = stateBlockMetaById[blockId];
  const requestedLayout = props.layout;
  const defaultLayout = blockMeta.defaults.layout ?? "panel";
  const resolvedLayout =
    !requestedLayout || blockMeta.supportedLayouts.includes(requestedLayout)
      ? requestedLayout ?? defaultLayout
      : defaultLayout;

  if (requestedLayout && resolvedLayout !== requestedLayout) {
    console.warn(
      `[StateKit] "${blockMeta.componentName}" does not support the "${requestedLayout}" layout. Falling back to "${defaultLayout}".`,
    );
  }

  const mergedProps: BaseStateProps = mergeStateProps(
    { ...props, layout: resolvedLayout },
    blockMeta.defaults,
  );

  return (
    <StateBlockShell
      {...mergedProps}
      category={blockMeta.category}
      media={media}
      actions={actions}
    />
  );
}

// packages/vue/src/base/StatePresetBlock.vue
<script setup lang="ts">
import { computed } from "vue";
import {
  stateBlockMetaById,
  type BaseStateProps,
  type StateBlockId,
} from "@statekit/shared";
import StateBlockShell from "./StateBlockShell.vue";
import type { PresetStateBlockProps } from "../types";

interface Props extends PresetStateBlockProps {
  blockId: StateBlockId;
}

const props = defineProps<Props>();

const blockMeta = computed(() => stateBlockMetaById[props.blockId]);

const resolvedLayout = computed(() => {
  const requestedLayout = props.layout;
  const defaultLayout = blockMeta.value.defaults.layout ?? "panel";

  if (
    !requestedLayout ||
    blockMeta.value.supportedLayouts.includes(requestedLayout)
  ) {
    return requestedLayout ?? defaultLayout;
  }

  console.warn(
    `[StateKit] "${blockMeta.value.componentName}" does not support the "${requestedLayout}" layout. Falling back to "${defaultLayout}".`,
  );

  return defaultLayout;
});

const mergedProps = computed<BaseStateProps>(() => ({
  ...blockMeta.value.defaults,
  title: props.title ?? blockMeta.value.defaults.title,
  description: props.description ?? blockMeta.value.defaults.description,
  tone: props.tone ?? blockMeta.value.defaults.tone ?? "neutral",
  density: props.density ?? blockMeta.value.defaults.density ?? "cozy",
  layout: resolvedLayout.value,
  primaryAction:
    props.primaryAction === undefined
      ? blockMeta.value.defaults.primaryAction
      : props.primaryAction,
  secondaryAction:
    props.secondaryAction === undefined
      ? blockMeta.value.defaults.secondaryAction
      : props.secondaryAction,
}));
</script>

<template>
  <StateBlockShell v-bind="mergedProps" :category="blockMeta.category" />
</template>
